assistans/assistans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='base')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('set/', include('setbudgetapp.urls', namespace='set')),

    path('admin/', admin.site.urls),
]

assistans/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/friends/', authapp.list_friends, name='friends'),
    path('user/friandrequest/', authapp.friend_request, name='friendrequest'),
    path('user/request/', authapp.FriendRequestList.as_view(), name='request'),
    path('user/request/delete/<int:pk>/', authapp.FriendRequestDelete.as_view(),
         name='request_delete'),
    path('user/request/accepte/<int:pk>/',
         authapp.accept_friend_request, name='request_accepte')
    # path('user/friandrequest',
    #      authapp.FriendRequestCreate.as_view(), name='friendrequest'),
    # path('user/verify/<str:email>/<str:activate_code>/',
    #      authapp.verify, name='verify'),
]

assistans/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('description/', mainapp.description, name='description'),

]

assistans/authapp/models.py
from email import message
from django.db import models
from django.apps import apps
from django.contrib.auth.models import AbstractUser

# from mainapp.models import Budget
# Budget = apps.get_model('mainapp', 'Budget')


class User(AbstractUser):
    age = models.PositiveIntegerField('возраст', blank=True, null=True)
    # avatar = models.ImageField(upload_to='avatars', blank=True)
    # activate_code = models.CharField(max_length=128, blank=True)
    registration_start_time = models.DateTimeField(
        auto_now_add=True, null=True)
    friends = models.ManyToManyField('User', blank=True)
    basic_budget = models.ForeignKey(
        'mainapp.Budget', on_delete=models.CASCADE, blank=True, null=True)


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'W'

    GENDER_CHOICES = (
        (MALE, 'мужской'),
        (FEMALE, 'женский'),
    )

    user = models.OneToOneField(
        User, primary_key=True, on_delete=models.CASCADE)
    tagline = models.CharField(verbose_name='теги',
                               max_length=128, blank=True)
    about_me = models.TextField(verbose_name='о себе', blank=True)
    gender = models.CharField(verbose_name='пол', max_length=1,
                              choices=GENDER_CHOICES, blank=True)


class FriendRequest(models.Model):
    from_user = models.ForeignKey(
        User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(
        User, related_name='to_user', on_delete=models.CASCADE)
    message_request = models.TextField(verbose_name='сообщение', blank=True)
    is_active = models.BooleanField(default=True)
    date_request = models.DateTimeField(auto_now_add=True, editable=False)
    accepte = models.BooleanField(default=False)

assistans/authapp/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms import HiddenInput, forms, ModelForm

from authapp.models import UserProfile, FriendRequest


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'


class AgeValidatorMixin:
    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age and age < 18:
            raise forms.ValidationError('Вы слишком молоды!')
        return age


class UserCreationForm(AgeValidatorMixin, UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "first_name", "password1",
                  "password2", "email", "age")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''


class UserChangeForm(AgeValidatorMixin, UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ("username", "password", "email", "first_name", "last_name",
                  "age")
        # fields = ("username", "password", "email", "first_name", "last_name",
        #           "age", "avatar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'password':
                field.widget = HiddenInput()
                continue
            field.widget.attrs['class'] = f'form-control {field_name}'
            field.help_text = ''


class UserProfileChangeForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'user':
                field.widget = HiddenInput()
                continue
            field.widget.attrs['class'] = f'form-control {field_name}'


class FriendRequestCreateForm(AuthenticationForm, ModelForm):
    class Meta:
        model = FriendRequest
        fields = ('to_user', 'message_request')

assistans/authapp/views.py
from curses.ascii import US
from django.db.models import Q
from multiprocessing import context
from django.contrib import auth
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DeleteView, CreateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test

from authapp.forms import UserLoginForm, UserCreationForm, UserChangeForm, UserProfileChangeForm, FriendRequestCreateForm
from authapp.models import User, UserProfile, FriendRequest


def login(request):
    redirect_to = request.GET.get('next', '')

    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST.get('username')
            password = request.POST.get('password')
            redirect_to = request.POST.get('redirect-to')
            user = auth.authenticate(username=username, password=password)
            if user and user.is_active:
                auth.login(request, user)
                return HttpResponseRedirect(redirect_to or reverse('base:index'))
    else:
        form = UserLoginForm()

    context = {
        'page_title': 'логин',
        'form': form,
        'redirect_to': redirect_to,
    }
    return render(request, 'authapp/login.html', context)


@login_required
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('base:index'))


def register(request):
    if request.method == 'POST':
        register_form = UserCreationForm(request.POST)
        # register_form = UserCreationForm(request.POST, request.FILES)
        if register_form.is_valid():
            # user = register_form.save(commit=False)
            # user.is_active = False
            # user.set_activation_code()
            register_form.save()
            # if not user.send_email_for_confirmation():
            #     return HttpResponseRedirect(reverse('auth:register'))
            return HttpResponseRedirect(reverse('base:index'))
    else:
        register_form = UserCreationForm()

    context = {
        'page_title': 'регистрация',
        'form': register_form,
    }
    return render(request, 'authapp/register.html', context)


@login_required
def edit(request):
    if request.method == 'POST':
        form = UserChangeForm(
            request.POST, request.FILES, instance=request.user)
        profile_form = UserProfileChangeForm(request.POST, request.FILES,
                                             instance=request.user.userprofile)
        if form.is_valid() and profile_form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('base:index'))
    else:
        form = UserChangeForm(instance=request.user)
        profile_form = UserProfileChangeForm(
            instance=request.user.userprofile)

    context = {
        'page_title': 'редактирование',
        'form': form,
        'profile_form': profile_form,
    }
    return render(request, 'authapp/update.html', context)


@login_required
def list_friends(request):
    user = request.user
    # friends = FriendRequest.objects.filter(
    #     from_user=user, to_user=user, accepte=True).all()
    # friends_user = friends.select_related('from_user').select_related(
    #     'to_user').exclude(from_user=user, to_user=user)

    friends = user.friends.all()

    context = {
        'friends': friends
    }
    return render(request, 'authapp/friends_list.html', context)


@login_required
def friend_request(request):
    text_error = ''
    if request.method == 'POST':
        name_user = request.POST.get('name')
        user = request.user
        print(f'form: {name_user}')

        friend = user.friends.all()

        requested_user = User.objects.filter(username=name_user).first()
        requests_exist = FriendRequest.objects.filter(
            from_user=user, to_user=requested_user).first()

        if requested_user and not friend and not requests_exist:

            friends = FriendRequest.objects.filter(
                from_user=user, to_user=user, accepte=True).select_related(
                'from_user').select_related(
                'to_user').exclude(from_user=user, to_user=user)

            create_request = FriendRequest()
            create_request.from_user = user
            create_request.to_user = requested_user
            create_request.save()
            return HttpResponseRedirect(reverse('authapp:friends'))
        text_error = 'Такого пользователя нет. Попробуйте еще'

    context = {
        'page_title': 'запрос',
        'text_error': text_error,
    }
    return render(request, 'authapp/friendrequest_form.html', context)
    # return HttpResponseRedirect(reverse('authapp:friends'))


@login_required
def accept_friend_request(request, pk):
    friend_request = FriendRequest.objects.get(id=pk)
    friend_request.to_user.friends.add(friend_request.from_user)
    friend_request.from_user.friends.add(friend_request.to_user)
    friend_request.is_active = False
    friend_request.accepte = True
    friend_request.save()
    return HttpResponseRedirect(reverse('auth:request'))


class UserIsAuthMixin:
    @method_decorator(user_passes_test(lambda user: user.is_authenticated))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PageTitleMixin:
    page_title_key = 'page_title'
    page_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.page_title_key] = self.page_title
        return context


class FriendRequestList(UserIsAuthMixin, PageTitleMixin, ListView):
    model = FriendRequest
    page_title = 'пользователь/запросы'

    def get_queryset(self):
        friends = FriendRequest.objects.filter(
            Q(from_user=self.request.user) |
            Q(to_user=self.request.user)).filter(is_active=True).all()
        return friends


class FriendRequestDelete(UserIsAuthMixin, PageTitleMixin, DeleteView):
    model = FriendRequest
    success_url = reverse_lazy('auth:request')
    page_title = 'пользователь/запросы/удаление'


# def friend_budget

# class FriendRequestCreate(UserIsAuthMixin, PageTitleMixin, CreateView):
#     model = FriendRequest
#     form_class = FriendRequestCreateForm
#     success_url = reverse_lazy('auth:friends')
#     page_title = 'пользователь/запрос'

#     def form_valid(self, form):
#         obj = form.save(commit=False)
#         obj.from_user = self.request.user
#         return super(FriendRequest, self).form_valid(form)


# class FriendList(UserIsAuthMixin, PageTitleMixin, ListView):
#     model = FriendRequest
#     page_title = 'пользователь/запрос'


# def verify(request, email, activate_code):
#     user = get_user_model().objects.filter(email=email).first()
#     if user.activate_code == activate_code and not user.is_activation_key_expired:
#         user.is_active = True
#         user.save()
#         auth.login(request, user,
#                    backend='django.contrib.auth.backends.ModelBackend')
#     return render(request, 'authapp/verification.html')


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

assistans/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ page_title|capfirst }}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="box">
    <ul class="menu">
        <li><a href="{% url 'base:description' %}" >
            {% if request.resolver_match.url_name == 'login' %}описание{% endif %}</a>
        </li>
    </ul>
    <div class="container">
        <div class="login">
            {% block container %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>

assistans/authapp/templates/authapp/base_user.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ page_title|capfirst }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
<div class="admin_container">
    <div class="h2 text-center head">
        Ваши друзья
    </div>
    {% block menu %}
        <div class="admin_menu">
            {% include 'authapp/includes/menu.html' %}
        </div>
    {% endblock %}

    {% block container %}
    {% endblock %}

</div>
</body>
</html>

assistans/authapp/templates/authapp/friendrequest_confirm_delete.html
v{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить запрос <b>{{ object.from_user }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'auth:request' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

assistans/authapp/templates/authapp/friendrequest_form.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="h2 text-center head">
        Запрос в друзья
    </div>
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            ...Наберите имя пользователя
            {% csrf_token %}
            <input id="POST-name" type="text" name="name">
            {% comment %} {{ form.as_p }} {% endcomment %}
            <p> {{text_error}} </p>
            <input class="form-control" type="submit" value="отправить запрос">
        </form>
        <a href="{% url 'auth:friends' %}"
           class="btn btn-primary form-control last">
            к друзьям
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/authapp/templates/authapp/friendrequest_list.html
{% extends 'authapp/base_user.html' %}
{% load static %}
{% comment %} {% load my_tags %} {% endcomment %}

{% block container %}
    <div class="users_list">
        {% for object in object_list %}
            {% if object.to_user == user %} 
                Запрос к вам в друзья
            {% else %}
                Ваш запрос     
            {% endif %} 
            <div class="product_record ">
                {% comment %} <img src="/media/{{ budget.image|default:'products_images/default.jpg' }}" alt="{{ budget.name }}"> {% endcomment %}
                <div class="product_name">
                    {{ object.from_user|title }}
                </div>
                <div class="product_actions">
                    {% if object.to_user == user %} 
                        <button>
                            <a href={% url 'auth:request_accepte' pk=object.pk %}>принять</a>
                        </button>
                    {% endif %}
                    <button>
                        <a href={% url 'auth:request_delete' pk=object.pk %}>удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>дата</b>
                    <p>{{ object.date_request }} руб</p>
                    <b>пользователю</b>
                    <p>{{ object.to_user }}</p>
                </div>
            </div>
               
        {% endfor %}
    </div>
{% endblock %}

assistans/authapp/templates/authapp/friends_list.html
{% extends 'authapp/base_user.html' %}
{% load static %}
{% comment %} {% load my_tags %} {% endcomment %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'auth:friendrequest' %}" class="btn btn-primary new_user">
            добавить друга
        </a>
        {% for shop_user in friends %}
            <div class="user_record {% if not shop_user.is_active %}not_active{% endif %}">
                {% comment %} <img src="{{ shop_user.avatar|media_folder_users }}"
                     alt="{{ shop_user.username }}"> {% endcomment %}
                <div class="user_role">
                    {% if shop_user.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <a href="{#% url 'new_admin:user_update' shop_user.pk %#}"
                       class="btn btn-primary">
                        Общие буджеты
                    </a>
                    <a href="{#% url 'new_admin:user_delete' shop_user.pk %#}"
                       class="btn btn-danger">
                        удалить
                    </a>
                </div>
                <div class="user_name">
                    <p><strong>{{ shop_user.username }}</strong></p>
                    <p>
                        {% if shop_user.first_name %}
                            <b>{{ shop_user.first_name|capfirst }}</b>
                            {% if shop_user.last_name %}
                                <p>{{ shop_user.last_name|capfirst }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ shop_user.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ shop_user.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ shop_user.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

assistans/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block container %}
    <div class="h2 text-center head">
        Вход в систему
    </div>
    <form class="form-horizontal" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        {% if redirect_to %}
            <input type="hidden" name="redirect-to" value="{{ redirect_to }}">
        {% endif %}
        <input class="form-control" type="submit" value="войти">
    </form>
    <a href="{% url 'auth:register' %}"
       class="btn btn-round form-control">
        зарегистрироваться
    </a>
    {% comment %} <a href="{% url 'social:begin' 'google-oauth2' %}?next=/"
       class="btn btn-round form-control">
        Google+
    </a> {% endcomment %}

{% endblock %}

assistans/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block container %}
    <div class="h2 text-center head">
        Регистрация
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <input class="form-control" type="submit" value="зарегистрироваться">
    </form>
    <a href="{% url 'base:index' %}"
       class="btn btn-round form-control">
        на главную
    </a>

{% endblock %}

assistans/authapp/templates/authapp/update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block container %}
    <div class="h2 text-center head">
        Редактирование профиля
    </div>
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {{ profile_form.as_p }}
        <br>
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <a href="{% url 'base:index' %}"
       class="btn btn-round form-control">
        на главную
    </a>
{% endblock %}

assistans/authapp/templates/authapp/verification.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}


{% block container %}
    {% if user.is_authenticated %}
        <h3>Поздравляем!</h3>
        <br>
        <h4>Пользователь {{ user.username }} подтвержден.</h4>
    {% else %}
        <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <a href="{% url 'base:index' %}" class="btn btn-round form-control">
        на главную
    </a>


{% endblock %}