assistans/assistans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='base')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('set/', include('setbudgetapp.urls', namespace='set')),

    path('admin/', admin.site.urls),
]

assistans/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/friends/', authapp.list_friends, name='friends'),
    path('user/friandrequest/', authapp.friend_request, name='friendrequest'),
    path('user/request/', authapp.FriendRequestList.as_view(), name='request'),
    path('user/request/delete/<int:pk>/', authapp.FriendRequestDelete.as_view(),
         name='request_delete'),
    path('user/request/accepte/<int:pk>/',
         authapp.accept_friend_request, name='request_accepte')
    # path('user/friandrequest',
    #      authapp.FriendRequestCreate.as_view(), name='friendrequest'),
    # path('user/verify/<str:email>/<str:activate_code>/',
    #      authapp.verify, name='verify'),
]

assistans/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('description/', mainapp.description, name='description'),

]

assistans/setbudgetapp/urls.py
from django.urls import path

import setbudgetapp.views as setbudgetapp

app_name = 'setbudgetapp'

urlpatterns = [
    path('', setbudgetapp.index, name='index'),
    path('budget/create/', setbudgetapp.BudgetCreate.as_view(),
         name='budget_create'),
    path('budget/update/<int:pk>/', setbudgetapp.BudgetUpdate.as_view(),
         name='budget_update'),
    path('budget/delete/<int:pk>/', setbudgetapp.BudgetDelete.as_view(),
         name='budget_delete'),
    path('budget/basic/<int:pk>/',
         setbudgetapp.set_basic_budget, name='basic_budget'),

    path('budget/<int:pk>/source/', setbudgetapp.source_list,
         name='source_list'),
    #     path('budget/source/<int:pk>/create/', setbudgetapp.SourceCreate.as_view(),
    #          name='source_create'),
    path('budget/<int:budget_pk>/source/create/', setbudgetapp.source_create,
         name='source_create'),
    #     path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.source_update,
    #          name='source_update'),
    path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.SourceUpdate.as_view(),
         name='source_update'),
    path('budget/source/delete/<int:pk>/', setbudgetapp.SourceDelete.as_view(),
         name='source_delete'),

    path('budget/<int:budget_pk>/source/items/<int:pk>/',
         setbudgetapp.ExpenseIncomeList.as_view(), name='source_details'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createExpense/', setbudgetapp.ExpenseCreate.as_view(),
         name='expense_create'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createIncome/', setbudgetapp.IncomeCreate.as_view(),
         name='income_create'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/update/', setbudgetapp.ExpenseIncomeUpdate.as_view(),
         name='item_update'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/delete/', setbudgetapp.ExpenseIncomeDelete.as_view(),
         name='item_delete'),

    path('category/',
         setbudgetapp.CategoryList.as_view(), name='category'),
    path('category/create/',
         setbudgetapp.CategoryCreate.as_view(), name='category_create'),
    path('category/update/<int:pk>/',
         setbudgetapp.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<int:pk>/',
         setbudgetapp.CategoryDelete.as_view(), name='category_delete'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),


]

assistans/setbudgetapp/models.py
from django.db import models

# Create your models here.

assistans/mainapp/views.py
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings

from mainapp.models import Budget, ExpenseIncome


@login_required
def index(request):
    '''
    The user's home page for displaying basic information
    '''

    # if not request.user.is_authenticated:
    #     return HttpResponseRedirect(reverse('auth:login'))
    # print(request.user)
    page_num = request.GET.get('page')
    budget_exists = True

    budget = request.user.basic_budget
    if not budget:
        budget_exists = False
        source = False
        total_amount = 0
        expense_income = False
    else:
        total_amount = budget.get_total_amount
        source = budget.source_set.filter(budget=budget.pk).first()

        source_name = list(
            name.id for name in budget.source_set.filter(budget=budget.pk))
        # expense_income = request.user.expenseincome_set.filter(
        #     source__id__in=source_name).order_by('-add_date')
        expense_income = ExpenseIncome.objects.filter(
            source__id__in=source_name).order_by('-add_date')

        expense_income_paginator = Paginator(expense_income, 10)
        try:
            expense_income = expense_income_paginator.get_page(page_num)
        except PageNotAnInteger:
            expense_income = expense_income_paginator.get_page(1)
        except EmptyPage:
            expense_income = expense_income_paginator.get_page(
                expense_income_paginator.num_pages)

    context = {
        'budget_exists': budget_exists,
        'budget': budget,
        'page_title': 'главная',
        'total_amount': total_amount,
        'source': source,
        'expense_income': expense_income
    }
    return render(request, 'mainapp/index.html', context)


def description(request):
    root_project = settings.SITE_ROOT[:-10]

    file = f'{root_project}/configs/description.txt'
    with open(file, 'r') as f:
        description = f.read()

    contacts = [
        {'city': 'Санкт-петербург',
         'phone': '+7-123-456-7890',
         'email': 'infoS@basketballshop',
         'address': 'Эрмитаж', },
    ]
    context = {
        'page_title': 'контакты',
        'contacts': contacts,
        'description': description,
    }
    return render(request, 'mainapp/contact.html', context)

assistans/setbudgetapp/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from django.contrib.auth import get_user_model


from setbudgetapp.forms import BudgetCreateForm, SourceCreateForm, ExpenseIncomeCreateForm, CategoryCreateForm
from mainapp.models import Budget, Source, ExpenseIncome, Category


@login_required
def index(request):
    all_budgets = Budget.objects.filter(
        Q(user_created=request.user) | Q(users=request.user)).all()
    context = {
        'page_title': 'настройки',
        'all_budgets': all_budgets,
    }
    return render(request, 'setbudgetapp/index.html', context)


@login_required
def set_basic_budget(request, pk):
    user = get_user_model().objects.get(id=request.user.id)
    user.basic_budget = Budget.objects.get(id=pk)
    user.save()
    return HttpResponseRedirect(reverse('set:index'))


class UserIsAuthMixin:
    @method_decorator(user_passes_test(lambda user: user.is_authenticated))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class PageTitleMixin:
    page_title_key = 'page_title'
    page_title = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context[self.page_title_key] = self.page_title
        return context


class BudgetCreate(UserIsAuthMixin, PageTitleMixin, CreateView):
    model = Budget
    form_class = BudgetCreateForm
    success_url = reverse_lazy('set:index')
    page_title = 'управление/бюджет/создание'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user_created = self.request.user
        return super(BudgetCreate, self).form_valid(form)

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""

        kwargs = super(BudgetCreate, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(BudgetCreate, self).get_context_data(**kwargs)
        context['update'] = False
        return context


class BudgetUpdate(UserIsAuthMixin, PageTitleMixin, UpdateView):
    model = Budget
    form_class = BudgetCreateForm
    success_url = reverse_lazy('set:index')
    page_title = 'управление/бюджет/редактирование'

    def get_form_kwargs(self):
        """ Passes the request object to the form class.
         This is necessary to only display members that belong to a given user"""
        kwargs = super(BudgetUpdate, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(BudgetUpdate, self).get_context_data(**kwargs)
        context['update'] = True
        return context


class BudgetDelete(UserIsAuthMixin, PageTitleMixin, DeleteView):
    model = Budget
    success_url = reverse_lazy('set:index')
    page_title = 'управление/бюджет/удаление'


class SourceDelete(UserIsAuthMixin, PageTitleMixin, DeleteView):
    model = Source
    # success_url = reverse_lazy('set:source_list')
    page_title = 'управление/бюджет/источник/удаление'

    def get_success_url(self):
        return reverse('set:source_list', kwargs={'pk': self.object.budget.pk})


class SourceUpdate(UserIsAuthMixin, PageTitleMixin, UpdateView):
    model = Source
    form_class = SourceCreateForm
    template_name = 'mainapp/source_form.html'
    # success_url = reverse_lazy(self.request.META.get('HTTP_REFERER'))
    page_title = 'управление/бюджет/источник/редактирование'

    def get_success_url(self):
        return reverse('set:source_list', kwargs={'pk': self.object.budget.pk})

    def get_context_data(self, **kwargs):
        context = super(SourceUpdate, self).get_context_data(**kwargs)
        context['budget_pk'] = self.request.resolver_match.kwargs['budget_pk']
        return context


@login_required
def source_list(request, pk):
    budget_pk = pk
    budget = get_object_or_404(Budget, pk=budget_pk)
    object_list = budget.source_set.all()
    context = {
        'page_title': 'управление/бюджет/источники',
        'budget_pk': budget_pk,
        'object_list': object_list,
    }
    return render(request, 'mainapp/source_list.html', context)


@login_required
def source_create(request, budget_pk):
    budget = get_object_or_404(Budget, pk=budget_pk)
    budget_pk = budget.pk
    if request.method == 'POST':
        form = SourceCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse(
                'set:source_list',
                kwargs={'pk': budget.pk}
            ))
    else:
        form = SourceCreateForm(
            initial={
                'budget': budget,
            }
        )

    context = {
        'page_title': 'управление/бюджет/источник/создание',
        'form': form,
        'budget_pk': budget_pk,
    }
    return render(request, 'mainapp/source_form.html', context)


class ExpenseIncomeList(UserIsAuthMixin, PageTitleMixin, ListView):
    model = ExpenseIncome
    # template_name = 'xxxx_app/xxxx.html'
    page_title = 'управление/бюджет/источник/детали'
    # queryset = ExpenseIncome.objects.filter(source=self.object.source.pk)

    def get_queryset(self):
        return ExpenseIncome.objects.filter(source=self.request.resolver_match.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(ExpenseIncomeList, self).get_context_data(**kwargs)
        context['budget_pk'] = self.request.resolver_match.kwargs['budget_pk']
        context['source_pk'] = self.request.resolver_match.kwargs['pk']
        # print(context)
        return context


class ExpenseIncomeCreateMixin:
    model = ExpenseIncome
    form_class = ExpenseIncomeCreateForm
    http_referer = ''

    def get_success_url(self):
        # print(self.request.META.get('HTTP_REFERER'))
        print(self.request.POST.get('next'))

        if '/set' in self.request.POST.get('next'):
            return reverse('set:source_details',
                           kwargs={'pk': self.object.source.pk,
                                   'budget_pk': self.object.source.budget.pk})
        else:
            return reverse('base:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['budget_pk'] = self.request.resolver_match.kwargs['budget_pk']
        context['source_pk'] = self.request.resolver_match.kwargs['source_pk']
        context['url'] = self.request.META.get('HTTP_REFERER')
        return context

    def get_initial(self):
        # self.http_referer = self.request.POST.get('next')
        initial = super().get_initial()
        initial = initial.copy()
        initial['source'] = self.request.resolver_match.kwargs['source_pk']
        return initial


class IncomeCreate(UserIsAuthMixin, PageTitleMixin, ExpenseIncomeCreateMixin, CreateView):
    model = ExpenseIncome
    form_class = ExpenseIncomeCreateForm
    template_name = 'mainapp/income_form.html'
    page_title = 'управление/бюджет/источник/детали/создание'

    def form_valid(self, form):
        self.http_referer = self.request.POST.get('next')
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.expense = False
        return super(IncomeCreate, self).form_valid(form)


class ExpenseCreate(UserIsAuthMixin, PageTitleMixin, ExpenseIncomeCreateMixin, CreateView):
    model = ExpenseIncome
    form_class = ExpenseIncomeCreateForm
    template_name = 'mainapp/expense_form.html'
    page_title = 'управление/бюджет/источник/детали/создание'

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        obj.expense = True
        return super(ExpenseCreate, self).form_valid(form)


class ExpenseIncomeUpdate(UserIsAuthMixin, PageTitleMixin, UpdateView):
    model = ExpenseIncome
    form_class = ExpenseIncomeCreateForm
    template_name = 'mainapp/expense_form.html'
    # success_url = reverse_lazy(self.request.META.get('HTTP_REFERER'))
    page_title = 'управление/бюджет/источник/редактирование'

    def get_success_url(self):
        return reverse('set:source_details',
                       kwargs={'pk': self.object.source.pk,
                               'budget_pk': self.object.source.budget.pk})

    def get_context_data(self, **kwargs):
        context = super(ExpenseIncomeUpdate, self).get_context_data(**kwargs)
        context['budget_pk'] = self.request.resolver_match.kwargs['budget_pk']
        # context['source_pk'] = self.request.resolver_match.kwargs['source_pk']
        return context


class ExpenseIncomeDelete(UserIsAuthMixin, PageTitleMixin, DeleteView):
    model = ExpenseIncome
    template_name = 'mainapp/expenseincome_delete.html'
    page_title = 'управление/бюджет/источник/детали/удаление'

    def get_success_url(self):
        return reverse('set:source_details',
                       kwargs={'pk': self.object.source.pk,
                               'budget_pk': self.request.resolver_match.kwargs['budget_pk']})

    def get_context_data(self, **kwargs):
        context = super(ExpenseIncomeList, self).get_context_data(**kwargs)
        context['budget_pk'] = self.request.resolver_match.kwargs['budget_pk']
        context['source_pk'] = self.request.resolver_match.kwargs['pk']
        return context


class CategoryList(UserIsAuthMixin, PageTitleMixin, ListView):
    model = Category
    page_title = 'управление/категории'

assistans/setbudgetapp/templates/mainapp/budget_confirm_delete.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'set:index' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/budget_form.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        {% if update %}
            <a href="{% url 'set:basic_budget' object.pk %}"
                class="btn btn-primary form-control last">
                сделать основным
            </a>
        {% endif%}
        <a href="{% url 'set:index' %}"
           class="btn btn-primary form-control last">
            к бюджетам
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/category_confirm_delete.html
v{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'set:category' %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/category_form.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'set:category' %}"
           class="btn btn-primary form-control last">
            к категориям
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/category_list.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}
{% comment %} {% load my_tags %} {% endcomment %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'set:category_create' %}" class="btn btn-primary new_user">
            новый категория
        </a>

        {% for object in object_list %}
            <div class="product_record {% if object.is_active %}not_active{% endif %}">
                {% comment %} <img src="/media/{{ budget.image|default:'products_images/default.jpg' }}" alt="{{ budget.name }}"> {% endcomment %}
                <div class="product_name">
                    {{ object.name|title }}
                </div>
                <div class="product_actions">
                    {% comment %} <button>
                        <a href={#% url 'set:source_list' pk=budget.pk %#}>подробнее</a>
                    </button> {% endcomment %}
                    <button>
                        <a href={% url 'set:category_update' pk=object.pk %}>редактировать</a>
                    </button>
                    <button>
                        <a href={% url 'set:category_delete' pk=object.pk %}>удалить</a>
                    </button>
                </div>
                {% comment %} <div class="summary">
                    <b>сумма</b>
                    <p>{{ budget.amount }} руб</p>
                    <b>пользователь</b>
                    <p>{{ budget.user }}</p>
                </div> {% endcomment %}
                {% comment %} <div class="product_desc">
                    {{ budget.short_desc|capfirst }}
                </div>{% endcomment %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/expense_form.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{{ url }}">
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'set:source_list' budget_pk %}"
           class="btn btn-primary form-control last">
           к списку источников
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/expenseincome_delete.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.name }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'set:source_details' pk=object.source.pk budget_pk=budget_pk %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/expenseincome_list.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}
{% comment %} {% load my_tags %} {% endcomment %}

{% block container %}
    <div class="users_list">
        <a href="{% url 'set:expense_create' budget_pk source_pk %}" class="btn btn-primary new_user">
            добавить трату
        </a>
        <a href="{% url 'set:income_create' budget_pk source_pk %}" class="btn btn-primary new_user">
            добавить доход
        </a>

        {% for obgect in object_list %}
            <div class="product_record">
                {% comment %} <img src="/media/{{ obgect.image|default:'products_images/default.jpg' }}" alt="{{ obgect.name }}"> {% endcomment %}
                <div class="product_name">
                    {{ obgect.user.name|title }}
                </div>
                <div class="product_actions">
                    {% comment %} <button>
                        <a href={#% url 'set:source_list' pk=obgect.pk %#}>подробнее</a>
                    </button> {% endcomment %}
                    <button>
                        <a href={% url 'set:item_update' pk=obgect.pk budget_pk=budget_pk %}>редактировать</a>
                    </button>
                    <button>
                        <a href={% url 'set:item_delete' pk=obgect.pk budget_pk=budget_pk %}>удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>сумма</b>
                    <p>{{ obgect.amount }} руб</p>
                    <b>пользователь</b>
                    <p>{{ obgect.user }}</p>
                </div>
                
                <div class="product_desc">
                    {% if obgect.expense %}
                        Трата
                    {% else %}
                        Доход
                    {% endif %}
                </div>
                
            </div>
        {% endfor %}
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/income_form.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{{ url }}">
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'set:source_list' budget_pk %}"
           class="btn btn-primary form-control last">
           к списку источников
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/product_form.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'new_admin:category_products' object.category_id %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="new_category_form">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'new_admin:category_products' category.pk %}"
           class="btn btn-primary form-control last">
            к списку продуктов
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/source_confirm_delete.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="user_delete">
        Уверены, что хотите удалить <b>{{ object.name_source }}</b>?
        <form method="post">
            {% csrf_token %}
            <input class="btn btn-danger" type="submit" value="удалить">
        </form>
        <a href="{% url 'set:source_list' object.budget.pk %}" class="btn btn-success">
            отмена
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/source_form.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}

{% block menu %}
{% endblock %}

{% block container %}
    <div class="login">
        <form class="form-horizontal" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="form-control" type="submit" value="сохранить">
        </form>
        <a href="{% url 'set:source_list' budget_pk %}"
           class="btn btn-primary form-control last">
            к списку источников
        </a>
        <a href="{% url 'base:index' %}"
           class="btn btn-primary form-control last">
            На главную
        </a>
    </div>
{% endblock %}

assistans/setbudgetapp/templates/mainapp/source_list.html
{% extends 'setbudgetapp/base.html' %}
{% load static %}


{% block container %}
    <div class="users_list">
        <a class="btn btn-primary new_user"
           href={% url 'set:source_create' budget_pk%}>новый источник</a>
 
        {% for object in object_list %}
            <div class="product_record">
                <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
                <div class="product_name">
                    {{ object.name_source|title }}
                </div>
                <div class="product_actions">
                    <button>
                        <a href={% url 'set:source_details' pk=object.pk budget_pk=budget_pk %}>подробнее</a>
                    </button>
                    <button>
                        <a href={% url 'set:source_update' pk=object.pk budget_pk=budget_pk %}>редактировать</a>
                    </button>
                    <button>
                        <a href={% url 'set:source_delete' pk=object.pk %}>удалить</a>
                    </button>
                </div>
                <div class="summary">
                    <b>сумма</b>
                    <p>{{ object.amount_source }} руб</p>
                    {% comment %} <b>количество</b>
                    <p>{{ object.quantity }}</p>
                </div>
                <div class="product_desc">
                    {{ object.short_desc|capfirst }}{% endcomment %}
                </div>
            </div>
        {% endfor %}

    </div>
{% endblock %}