assistans/assistans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='base')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('set/', include('setbudgetapp.urls', namespace='set')),

    path('admin/', admin.site.urls),
]

assistans/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/friends/', authapp.list_friends, name='friends'),
    path('user/friandrequest/', authapp.friend_request, name='friendrequest'),
    path('user/request/', authapp.FriendRequestList.as_view(), name='request'),
    path('user/request/delete/<int:pk>/', authapp.FriendRequestDelete.as_view(),
         name='request_delete'),
    path('user/request/accepte/<int:pk>/',
         authapp.accept_friend_request, name='request_accepte')
    # path('user/friandrequest',
    #      authapp.FriendRequestCreate.as_view(), name='friendrequest'),
    # path('user/verify/<str:email>/<str:activate_code>/',
    #      authapp.verify, name='verify'),
]

assistans/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('description/', mainapp.description, name='description'),

]

assistans/setbudgetapp/urls.py
from django.urls import path

import setbudgetapp.views as setbudgetapp

app_name = 'setbudgetapp'

urlpatterns = [
    path('', setbudgetapp.index, name='index'),
    path('budget/create/', setbudgetapp.BudgetCreate.as_view(),
         name='budget_create'),
    path('budget/update/<int:pk>/', setbudgetapp.BudgetUpdate.as_view(),
         name='budget_update'),
    path('budget/delete/<int:pk>/', setbudgetapp.BudgetDelete.as_view(),
         name='budget_delete'),
    path('budget/basic/<int:pk>/',
         setbudgetapp.set_basic_budget, name='basic_budget'),

    path('budget/<int:pk>/source/', setbudgetapp.source_list,
         name='source_list'),
    #     path('budget/source/<int:pk>/create/', setbudgetapp.SourceCreate.as_view(),
    #          name='source_create'),
    path('budget/<int:budget_pk>/source/create/', setbudgetapp.source_create,
         name='source_create'),
    #     path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.source_update,
    #          name='source_update'),
    path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.SourceUpdate.as_view(),
         name='source_update'),
    path('budget/source/delete/<int:pk>/', setbudgetapp.SourceDelete.as_view(),
         name='source_delete'),

    path('budget/<int:budget_pk>/source/items/<int:pk>/',
         setbudgetapp.ExpenseIncomeList.as_view(), name='source_details'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createExpense/', setbudgetapp.ExpenseCreate.as_view(),
         name='expense_create'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createIncome/', setbudgetapp.IncomeCreate.as_view(),
         name='income_create'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/update/', setbudgetapp.ExpenseIncomeUpdate.as_view(),
         name='item_update'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/delete/', setbudgetapp.ExpenseIncomeDelete.as_view(),
         name='item_delete'),

    path('category/',
         setbudgetapp.CategoryList.as_view(), name='category'),
    path('category/create/',
         setbudgetapp.CategoryCreate.as_view(), name='category_create'),
    path('category/update/<int:pk>/',
         setbudgetapp.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<int:pk>/',
         setbudgetapp.CategoryDelete.as_view(), name='category_delete'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),


]

assistans/mainapp/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth import get_user_model
from authapp.models import User
from django.db import transaction


class Budget(models.Model):
    user_created = models.ForeignKey(get_user_model(),
                                     on_delete=models.CASCADE,
                                     related_name='budgets')
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    users = models.ManyToManyField(User, blank=True)
    amount = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)
    _total_amount = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)
    # main_budget = models.BooleanField(default=False)
    # sources_finance = models.ManyToManyField(Source)

    def calculation_total_amount(self):
        self._total_amount = self.amount + sum(
            map(lambda x: x.amount_source, self.source_set.all()))
        self.save()

    @property
    def get_total_amount(self):
        return self._total_amount

    # def save(self, *args, **kwargs):
    #     if not self.main_budget:
    #         return super(Budget, self).save(*args, **kwargs)
    #     with transaction.atomic():
    #         Budget.objects.filter(
    #             main_budget=True, user=self.user).update(main_budget=False)
    #         return super(Budget, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Source(models.Model):
    budget = models.ForeignKey(
        Budget, on_delete=models.CASCADE)
    name_source = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    amount_source = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)

    def calculation_amount(self):
        self.amount_source = sum(
            map(lambda x: (float(x.amount) * (-1 if x.expense else 1)),
                self.expenseincome_set.all()))
        self.save()

    def __str__(self):
        return self.name_source


class Category(models.Model):
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)

    def __str__(self):
        return self.name


class ExpenseIncome(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expense = models.BooleanField(default=True)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    date_event = models.DateField(
        'время события', blank=True, null=True, default=None)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(
        'сумма траты', max_digits=12, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        super(ExpenseIncome, self).save(*args, **kwargs)
        source = Source.objects.filter(pk=self.source.pk).first()
        budget = Budget.objects.filter(pk=source.budget.pk).first()
        source.calculation_amount()
        budget.calculation_total_amount()


class Spent(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    amount_spent = models.DecimalField(
        'сумма траты', max_digits=12, decimal_places=2, default=0)
    # date_spent = models.DateTimeField('время', auto_now_add=True)


class Deposit(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    amount_deposit = models.DecimalField(
        'сумма добавления', max_digits=12, decimal_places=2, default=0)
    # date_deposit = models.DateTimeField('время', auto_now_add=True)

assistans/mainapp/views.py
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings

from mainapp.models import Budget, ExpenseIncome


@login_required
def index(request):
    '''
    The user's home page for displaying basic information
    '''

    # if not request.user.is_authenticated:
    #     return HttpResponseRedirect(reverse('auth:login'))
    # print(request.user)
    page_num = request.GET.get('page')
    budget_exists = True

    budget = request.user.basic_budget
    if not budget:
        budget_exists = False
        source = False
        total_amount = 0
        expense_income = False
    else:
        total_amount = budget.get_total_amount
        source = budget.source_set.filter(budget=budget.pk).first()

        source_name = list(
            name.id for name in budget.source_set.filter(budget=budget.pk))
        # expense_income = request.user.expenseincome_set.filter(
        #     source__id__in=source_name).order_by('-add_date')
        expense_income = ExpenseIncome.objects.filter(
            source__id__in=source_name).order_by('-add_date')

        expense_income_paginator = Paginator(expense_income, 10)
        try:
            expense_income = expense_income_paginator.get_page(page_num)
        except PageNotAnInteger:
            expense_income = expense_income_paginator.get_page(1)
        except EmptyPage:
            expense_income = expense_income_paginator.get_page(
                expense_income_paginator.num_pages)

    context = {
        'budget_exists': budget_exists,
        'budget': budget,
        'page_title': 'главная',
        'total_amount': total_amount,
        'source': source,
        'expense_income': expense_income
    }
    return render(request, 'mainapp/index.html', context)


def description(request):
    root_project = settings.SITE_ROOT[:-10]

    file = f'{root_project}/configs/description.txt'
    with open(file, 'r') as f:
        description = f.read()

    contacts = [
        {'city': 'Санкт-петербург',
         'phone': '+7-123-456-7890',
         'email': 'infoS@basketballshop',
         'address': 'Эрмитаж', },
    ]
    context = {
        'page_title': 'контакты',
        'contacts': contacts,
        'description': description,
    }
    return render(request, 'mainapp/contact.html', context)

assistans/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="utf-8">
	<title>
        {{ page_title|default:'магазин'|capfirst }}
    </title>
	    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
	<div class="box">
        {% block box %}
        {% endblock %}

		<div class="clr"></div>

	</div>

	<div class="footer">
		<div class="clearfix">
			<div class="text-footer">
				<h3>контакты</h3>
			</div>
			<div class="text-footer">
				<h3>полезная информация</h3>
			</div>
			<div class="text-footer clearfix">
				<h3>Оставайтесь на связи</h3>
				<p>Подписаться на новости и рассылки</p>
				<form>
					<input type="email" name="email" placeholder="ваш email">
					<a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
				</form>
			</div>
		</div>
		<p class="small">&copy; GB 2017</p>
		<div class="social">
			<a href="#" class="social1"></a>
			<a href="#" class="social2"></a>
			<a href="#" class="social3"></a>
			<a href="#" class="social4"></a>
		</div>
		<p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
	</div>

</body>

</html>

assistans/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block box %}
	<div class="hero">
		{% include 'mainapp/includes/main_menu.html' %}
		<h1>Описание</h1>
		<p> {{description}} </p>
	</div>
	
	

	<div class="location">
	{% for item in contacts %}
		<div class="location-1">
			<i class="fa fa-map-marker fa-5x"></i>
			<h4>{{ item.city }}</h4>
			<div class="contacts">
				<h5>Телефон</h5>
				<p>{{ item.phone }}</p>
			</div>
			<div class="contacts">
				<h5>Email</h5>
				<p>{{ item.email }}</p>
			</div>
			<div class="contacts">
				<h5>Адрес</h5>
				<p>{{ item.address }}</p>
			</div>
		</div>
	{% endfor %}
		
	</div>
{% endblock  %}

assistans/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block box %}

	<div class="splash-screen">
		{% include 'mainapp/includes/main_menu.html' %}
		<div class="text-splash-screen">
			<h3 class="big"> пользователь: {{ user.username|default:"пользователь"|title }}</h3>
			
			{% if not budget_exists %} 
				<p>У вас пока нет созданного бюджета, хотите создать бюджет?</p> 
				<a href="{% url 'set:budget_create' %}"
				class="button-order">создать<img src="{% static '/img/arrow.png' %}" alt=""></a>
			{% elif not source %} 
				<h3 class="big"> Ваш основной бюджет: {{ total_amount }} руб</h3>
				<p>У вас пока нет созданного бюджета, хотите создать бюджет?</p>
				<a href="{% url 'set:source_create' budget_pk=budget.pk%}"
				class="button-order"> источник <img src="{% static '/img/arrow.png' %}" alt=""></a>
			{% else %}
				<h3 class="big"> Ваш основной бюджет: {{ total_amount }} руб</h3>
				<a href="{% url 'set:income_create' budget_pk=budget.pk source_pk=source.pk %}"
				class="button-order">доход <img src="{% static '/img/arrow.png' %}" alt=""></a>
				<a href="{% url 'set:expense_create' budget_pk=budget.pk source_pk=source.pk %}"
				class="button-order">расход <img src="{% static '/img/arrow.png' %}" alt=""></a>
			{% endif %}
		</div>
	</div>

	{% if not expense_income %}
        <div class="h2 text-center head">
            Пока не чего нет
        </div>
    {% else %}
        <div class="h2 text-center head">
            Ваша активность {% comment %} {{ user.first_name|default:'пользователь'|title }} {% endcomment %}
        </div>
		<div class="paginator">
			{% if expense_income.has_previous %}
				<a href="{% url 'base:index' %}?page={{ expense_income.previous_page_number }}">
					<
				</a>
			{% endif %}
			<span class="current">страница {{ expense_income.number }} из {{ expense_income.paginator.num_pages }}</span>
			{% if expense_income.has_next %}
				<a href="{% url 'base:index' %}?page={{ expense_income.next_page_number }}">
					>
				</a>
			{% endif %}
		</div>
        <table class="table orders_list">
            <thead>
            <tr>
                <th>Пользователь</th>
                <th>Создан</th>
                <th>Сумма</th>
				<th>Источник</th>
                <th>Статус</th>
            </tr>
            </thead>
            <tbody>
            {% for item in expense_income %}
                <tr>
                    <td class="td1 orders_list">{{ item.user }}</td>
                    <td>{{ item.add_date|date:"Y-m-d H:i:s" }}</td>
                    <td>{{ item.amount }}</td>
                    <td>{{ item.source }}</td>
					<td>
						{% if item.expense %}
							Трата
						{% else %}
							Доход
						{% endif %}
					</td>
                    {% comment %} <td>
                        <a href="{#% url 'set:read' pk=item.pk %#}">
                            посмотреть
                        </a>
                    </td> {% endcomment %}
                    <td>
						<a href="{% url 'set:item_update' pk=item.pk budget_pk=budget.pk %}">
							редактировать
						</a>
                    </td>
                    {% comment %} <td>
						<a href="{% url 'set:item_delete' pk=item.pk budget_pk=budget.pk %}">
							удалить
						</a>
                    </td> {% endcomment %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock  %}