assistans/assistans/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('mainapp.urls', namespace='base')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('set/', include('setbudgetapp.urls', namespace='set')),

    path('admin/', admin.site.urls),
]

assistans/authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('user/register/', authapp.register, name='register'),
    path('user/edit/', authapp.edit, name='edit'),
    path('user/friends/', authapp.list_friends, name='friends'),
    path('user/friandrequest/', authapp.friend_request, name='friendrequest'),
    path('user/request/', authapp.FriendRequestList.as_view(), name='request'),
    path('user/request/delete/<int:pk>/', authapp.FriendRequestDelete.as_view(),
         name='request_delete'),
    path('user/request/accepte/<int:pk>/',
         authapp.accept_friend_request, name='request_accepte')
    # path('user/friandrequest',
    #      authapp.FriendRequestCreate.as_view(), name='friendrequest'),
    # path('user/verify/<str:email>/<str:activate_code>/',
    #      authapp.verify, name='verify'),
]

assistans/mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('description/', mainapp.description, name='description'),

]

assistans/setbudgetapp/urls.py
from django.urls import path

import setbudgetapp.views as setbudgetapp

app_name = 'setbudgetapp'

urlpatterns = [
    path('', setbudgetapp.index, name='index'),
    path('budget/create/', setbudgetapp.BudgetCreate.as_view(),
         name='budget_create'),
    path('budget/update/<int:pk>/', setbudgetapp.BudgetUpdate.as_view(),
         name='budget_update'),
    path('budget/delete/<int:pk>/', setbudgetapp.BudgetDelete.as_view(),
         name='budget_delete'),
    path('budget/basic/<int:pk>/',
         setbudgetapp.set_basic_budget, name='basic_budget'),

    path('budget/<int:pk>/source/', setbudgetapp.source_list,
         name='source_list'),
    #     path('budget/source/<int:pk>/create/', setbudgetapp.SourceCreate.as_view(),
    #          name='source_create'),
    path('budget/<int:budget_pk>/source/create/', setbudgetapp.source_create,
         name='source_create'),
    #     path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.source_update,
    #          name='source_update'),
    path('budget/<int:budget_pk>/source/update/<int:pk>/', setbudgetapp.SourceUpdate.as_view(),
         name='source_update'),
    path('budget/source/delete/<int:pk>/', setbudgetapp.SourceDelete.as_view(),
         name='source_delete'),

    path('budget/<int:budget_pk>/source/items/<int:pk>/',
         setbudgetapp.ExpenseIncomeList.as_view(), name='source_details'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createExpense/', setbudgetapp.ExpenseCreate.as_view(),
         name='expense_create'),
    path('budget/<int:budget_pk>/source/<int:source_pk>/items/createIncome/', setbudgetapp.IncomeCreate.as_view(),
         name='income_create'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/update/', setbudgetapp.ExpenseIncomeUpdate.as_view(),
         name='item_update'),
    path('budget/<int:budget_pk>/source/item/<int:pk>/delete/', setbudgetapp.ExpenseIncomeDelete.as_view(),
         name='item_delete'),

    path('category/',
         setbudgetapp.CategoryList.as_view(), name='category'),
    path('category/create/',
         setbudgetapp.CategoryCreate.as_view(), name='category_create'),
    path('category/update/<int:pk>/',
         setbudgetapp.CategoryUpdate.as_view(), name='category_update'),
    path('category/delete/<int:pk>/',
         setbudgetapp.CategoryDelete.as_view(), name='category_delete'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),
    #     path('budget/source/create/', setbudgetapp.ExpenseIncomeCreate.as_view(),
    #          name='expense_create'),


]

assistans/mainapp/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth import get_user_model
from authapp.models import User
from django.db import transaction


class Budget(models.Model):
    user_created = models.ForeignKey(get_user_model(),
                                     on_delete=models.CASCADE,
                                     related_name='budgets')
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    users = models.ManyToManyField(User, blank=True)
    amount = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)
    _total_amount = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)
    # main_budget = models.BooleanField(default=False)
    # sources_finance = models.ManyToManyField(Source)

    def calculation_total_amount(self):
        self._total_amount = self.amount + sum(
            map(lambda x: x.amount_source, self.source_set.all()))
        self.save()

    @property
    def get_total_amount(self):
        return self._total_amount

    # def save(self, *args, **kwargs):
    #     if not self.main_budget:
    #         return super(Budget, self).save(*args, **kwargs)
    #     with transaction.atomic():
    #         Budget.objects.filter(
    #             main_budget=True, user=self.user).update(main_budget=False)
    #         return super(Budget, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Source(models.Model):
    budget = models.ForeignKey(
        Budget, on_delete=models.CASCADE)
    name_source = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    amount_source = models.DecimalField(
        'общая сумма', max_digits=15, decimal_places=2, default=0)

    def calculation_amount(self):
        self.amount_source = sum(
            map(lambda x: (float(x.amount) * (-1 if x.expense else 1)),
                self.expenseincome_set.all()))
        self.save()

    def __str__(self):
        return self.name_source


class Category(models.Model):
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)

    def __str__(self):
        return self.name


class ExpenseIncome(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    expense = models.BooleanField(default=True)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    date_event = models.DateField(
        'время события', blank=True, null=True, default=None)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    amount = models.DecimalField(
        'сумма траты', max_digits=12, decimal_places=2, default=0)

    def save(self, *args, **kwargs):
        super(ExpenseIncome, self).save(*args, **kwargs)
        source = Source.objects.filter(pk=self.source.pk).first()
        budget = Budget.objects.filter(pk=source.budget.pk).first()
        source.calculation_amount()
        budget.calculation_total_amount()


class Spent(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    amount_spent = models.DecimalField(
        'сумма траты', max_digits=12, decimal_places=2, default=0)
    # date_spent = models.DateTimeField('время', auto_now_add=True)


class Deposit(models.Model):
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    description = models.TextField('описание', blank=True)
    add_date = models.DateTimeField('время', auto_now_add=True)
    amount_deposit = models.DecimalField(
        'сумма добавления', max_digits=12, decimal_places=2, default=0)
    # date_deposit = models.DateTimeField('время', auto_now_add=True)

assistans/mainapp/views.py
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings

from mainapp.models import Budget, ExpenseIncome


@login_required
def index(request):
    '''
    The user's home page for displaying basic information
    '''

    # if not request.user.is_authenticated:
    #     return HttpResponseRedirect(reverse('auth:login'))
    # print(request.user)
    page_num = request.GET.get('page')
    budget_exists = True

    budget = request.user.basic_budget
    if not budget:
        budget_exists = False
        source = False
        total_amount = 0
        expense_income = False
    else:
        total_amount = budget.get_total_amount
        source = budget.source_set.filter(budget=budget.pk).first()

        source_name = list(
            name.id for name in budget.source_set.filter(budget=budget.pk))
        # expense_income = request.user.expenseincome_set.filter(
        #     source__id__in=source_name).order_by('-add_date')
        expense_income = ExpenseIncome.objects.filter(
            source__id__in=source_name).order_by('-add_date')

        expense_income_paginator = Paginator(expense_income, 10)
        try:
            expense_income = expense_income_paginator.get_page(page_num)
        except PageNotAnInteger:
            expense_income = expense_income_paginator.get_page(1)
        except EmptyPage:
            expense_income = expense_income_paginator.get_page(
                expense_income_paginator.num_pages)

    context = {
        'budget_exists': budget_exists,
        'budget': budget,
        'page_title': 'главная',
        'total_amount': total_amount,
        'source': source,
        'expense_income': expense_income
    }
    return render(request, 'mainapp/index.html', context)


def description(request):
    root_project = settings.SITE_ROOT[:-10]

    file = f'{root_project}/configs/description.txt'
    with open(file, 'r') as f:
        description = f.read()

    contacts = [
        {'city': 'Санкт-петербург',
         'phone': '+7-123-456-7890',
         'email': 'infoS@basketballshop',
         'address': 'Эрмитаж', },
    ]
    context = {
        'page_title': 'контакты',
        'contacts': contacts,
        'description': description,
    }
    return render(request, 'mainapp/contact.html', context)

assistans/mainapp/templates/mainapp/includes/catalog_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'base:category' 0 %}"
               class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == 0 %}active{% endif %}">
                все
            </a>
        </li>

        {% for item in menu %}
            <li>
                <a href="{% url 'base:category' item.pk %}"
                   class="{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == item.pk %}active{% endif %}">
                    {{ item.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

assistans/mainapp/templates/mainapp/includes/main_menu.html
<div class="header clearfix">
    <a href="{% url 'base:index' %}" class="logo"></a>
    <ul class="menu">
        {% if user.is_authenticated %}
            <li><a href="{% url 'base:index' %}" 
                class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}">
                главная</a>
            </li>
            <li><a href="{% url 'set:index' %}"
                class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
                управление</a>
            </li>
            <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                        {{ user.username|default:"пользователь"|title }}
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'auth:edit' %}">
                                профиль
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'auth:friends' %}">
                                друзья
                            </a>
                        </li>
                        {% comment %} <li>
                            <a href="{% url 'orders:index' %}">
                                что-то
                            </a>
                        </li> {% endcomment %}
                    </ul>
                </div>
            </li>
        {% endif %}
        {% comment %} {% if user.is_superuser %}
            <li>
                <a href="{% url 'new_admin:index' %}">
                    Админка
                </a>
            </li>
        {% endif %} {% endcomment %}
        <li><a href="{% url 'base:description' %}"
            class="{% if request.resolver_match.url_name == 'contact' %}active{% endif %}">
            описание</a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    выйти
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    войти
                </a>
            {% endif %}
        </li>

    </ul>
    <a href="#" class="search"></a>
    {% comment %} <a href="{% url 'basket:index' %}" class="basket">
        {% if user.is_authenticated %}
            <span>{{ user.basket_price|floatformat:0 }} руб ({{ user.basket_qty }} шт)</span>
        {% endif %}
    </a> {% endcomment %}
</div>